
Prix Moyen par Ville =
[Prix Moyen]

Écart vs Marché =
[Prix Moyen] - CALCULATE([Prix Moyen], ALL(v_annonces_full[ville]))


% Très Bas =
DIVIDE(
    CALCULATE([Total Annonces], v_annonces_full[categorie_prix] = "Très Bas"),
    [Total Annonces]
)

% Bas =
DIVIDE(
    CALCULATE([Total Annonces], v_annonces_full[categorie_prix] = "Bas"),
    [Total Annonces]
)

% Moyen =
DIVIDE(
    CALCULATE([Total Annonces], v_annonces_full[categorie_prix] = "Moyen"),
    [Total Annonces]
)

% Élevé =
DIVIDE(
    CALCULATE([Total Annonces], v_annonces_full[categorie_prix] = "Élevé"),
    [Total Annonces]
)

% Luxe =
DIVIDE(
    CALCULATE([Total Annonces], v_annonces_full[categorie_prix] = "Luxe"),
    [Total Annonces]
)

Prix Moyen Mensuel =
CALCULATE([Prix Moyen], v_annonces_full[prix_type] = "mensuel")

Prix Moyen Journalier =
CALCULATE([Prix Moyen], v_annonces_full[prix_type] = "journalier")

Indice Cherté =
DIVIDE(
    [Prix Moyen par m2],
    CALCULATE([Prix Moyen par m2], ALL(v_annonces_full[ville]))
)
